---
- name: Check resolv.conf file in /etc
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  serial: 5
  tasks:
    - name: Check resolv.conf file in /etc
      shell: |
        hostname_hostname=$(hostname)
        #date_current=$(df -Th | grep -i "10.250.33.193" || df -Th | grep -i "10.250.33.193")
        mountpoint=$(cat /etc/resolv.conf)
        echo "<tr><td>{{ inventory_hostname }}</td><td>${hostname_hostname}</td><td>${mountpoint}</td></tr>"

      register: multicast_status
      ignore_errors: yes

    - name: Set multicast check results
      set_fact:
        multicast_row: "{{ multicast_status.stdout }}"

- name: Collect results and send email from single server
  hosts: 10.250.22.228
  become: yes
  gather_facts: no

  tasks:
    - name: Aggregate email body from all servers
      run_once: true
      delegate_to: 10.250.22.228
      set_fact:
        final_email_body: "<html><body><h2>Check resolv.conf file in /etc</h2><h5>AWX server Date and Time:- $(date)</h5><table border='1'><tr><th>IP address</th><th>Hostname</th><th>/etc/resolv.conf</th></tr>{% for host in groups['all'] %}{{ hostvars[host]['multicast_row'] | default('') }}{% endfor %}</table></body></html>"

    - name: Send Multicast Check Report Email
      run_once: true
      delegate_to: 10.250.22.228
      shell: |
        echo "{{ final_email_body }}" | /usr/local/bin/sendEmail -o tls=no -s 10.250.8.225:25 -f gaikwad.ajit@edelweissfin.com -u "Check resolv.conf file in /etc" -t treasury.infra@edelweissfin.com -o message-content-type=html
        #treasury.infra@edelweissfin.com -cc treasury_prod_support@edelweissfin.com -o message-content-type=html
        #gaikwad.ajit@edelweissfin.com -cc ashish.u@edelweissfin.com -o message-content-type=html
        #gaikwad.ajit@edelweissfin.com -o message-content-type=html
        #treasury.infra@edelweissfin.com -o message-content-type=html
